/* config-taglib.h. Generated by cmake from config-taglib.h.cmake */

/* Define if you have libz */
#define   HAVE_ZLIB 1

/* #undef NO_ITUNES_HACKS */
/* #undef WITH_ASF */
/* #undef WITH_MP4 */

#define TESTS_DIR "/home/mark/repos/taglib-1.8/tests/"

